version: '3.8'
name: redis_db

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_REPLICATION_MODE=master
    restart: always

volumes:
  redis_data:
    driver: local